# Generated by Django 5.1.4 on 2024-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMobilityCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_photo', models.ImageField(upload_to='student_mobility_courses/')),
                ('title', models.CharField(max_length=255)),
                ('title_heading_details', models.TextField()),
                ('description', models.TextField()),
                ('courses_included', models.TextField()),
                ('course_contents', models.TextField()),
                ('course_trainer', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='student_mobility_courses/')),
                ('image2', models.ImageField(upload_to='student_mobility_courses/')),
                ('image3', models.ImageField(upload_to='student_mobility_courses/')),
                ('image1_description', models.CharField(default='Image 1 description', max_length=255)),
                ('image2_description', models.CharField(default='Image 2 description', max_length=255)),
                ('image3_description', models.CharField(default='Image 3 description', max_length=255)),
            ],
        ),
    ]
