# Generated by Django 5.1.4 on 2024-12-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmobilitycourse',
            name='image1_description',
            field=models.CharField(blank=True, default='Image 1 description', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentmobilitycourse',
            name='image2_description',
            field=models.CharField(blank=True, default='Image 2 description', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentmobilitycourse',
            name='image3_description',
            field=models.CharField(blank=True, default='Image 3 description', max_length=255, null=True),
        ),
    ]
